type Recipe {
    id: ID
    name: String
    category: String
    servings: Int
    preparationTime: Int
    image: String
    ingredients: [String]
    steps: [String]
    nutritionalValues: [String]
    ratings: [Int]
    averageRating: Float
}
input IngredientInput {
    name: String!
    quantity: Float!
    unit: String!
}

input NutritionalValueInput {
    name: String!
    amount: Float!
    unit: String!
}
type CategoryCount {
    name: String
    count: Int
}

type Query {
    recipes(page: Int, size: Int): [Recipe]
    recipe(id: ID): Recipe
    searchRecipes(query: String): [Recipe]
    filterRecipes(category: String, sortBy: String): [Recipe]
    recipeCountByCategory: [CategoryCount]
    totalCount: Int
    averageRating: Float
}

type Mutation {
    createRecipe(
        name: String!
        category: String!
        servings: Int!
        preparationTime: Int!
        image: String
        ingredients: [IngredientInput]
        steps: [String]
        nutritionalValues: [NutritionalValueInput]
    ): Recipe

    updateRecipe(
        id: ID!
        name: String!
        category: String!
        servings: Int!
        preparationTime: Int!
        image: String
        ingredients: [IngredientInput]
        steps: [String]
        nutritionalValues: [NutritionalValueInput]
    ): Recipe

    deleteRecipe(id: ID!, userId:Int!): Boolean
    addRating(id: ID!, rating: Int!): Recipe
    startFaker: Boolean
    stopFaker: Boolean
}