spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/prepify
spring.datasource.username=root
spring.datasource.password=antonia12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/prepify_chat

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

server.ssl.key-store=classpath:prepify.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1
server.port=8443
server.address=0.0.0.0

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=szalokantonia72@gmail.com
spring.mail.password=odlf pnqp jetr csna
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App base URL (used in email links)
app.base-url=https://192.168.2.215:8443
frontend.base-url=http://localhost:5173